FROM ruby:2.7.2

ENV APP_ROOT=/rpd \
    LANG=ja_JP.UTF-8 \
    LC_CTYPE=ja_JP.UTF-8 \
    TZ=Asia/Tokyo

RUN apt-get update -qq && \
    apt-get install -y build-essential

RUN apt-get install -y wget apt-transport-https && \
    wget --quiet -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn postgresql-client imagemagick libpq-dev libvips-tools locales

RUN apt-get install -y task-japanese locales locales-all && \
    locale-gen ja_JP.UTF-8 && \
    /usr/sbin/update-locale LANG=ja_JP.UTF-8

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs

WORKDIR $APP_ROOT
COPY ./Gemfile* ${APP_ROOT}

RUN bundle install -j4 --retry 3
COPY . ${APP_ROOT}

# COPY container/rails/entrypoint.sh /usr/bin/entrypoint.sh
# RUN chmod +x /usr/bin/entrypoint.sh
# ENTRYPOINT ["entrypoint.sh"]

RUN yarn install

EXPOSE 3000 1234 26162

RUN git clone https://github.com/awslabs/git-secrets.git && \
    cd git-secrets && make install