version: '3'
services:
  # Rails 用コンテナ
  app:
    build:
      context: .
      dockerfile: containers/rails/Dockerfile
    container_name: rpd_app
    env_file: .env
    ports:
      - '3000:3000'
    # アプリケーションファイルの同期
    volumes:
      - .:/rpd
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
  # PostgreSQL 用コンテナ
  db:
    build:
      context: .
      dockerfile: containers/postgresql/Dockerfile
    container_name: rpd_db
    env_file: .env
    # 永続化ボリュームの定義
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  # データボリュームの登録
  db-data:
